### ISSUE TITLE
日期组件异常问题

### ISSUE THREAD

**Issue by qq1014022914** [ruisibi/datawrite#1]
使用日期组件的时候，会报save.action问题，尝试修改实体类中时间参数还是未得到解决
![QQ图片20240706084126](https://github.com/ruisibi/datawrite/assets/28436981/f5ffa049-482f-4d72-b6fe-056c93e9a33d)
![QQ图片20240706084135](https://github.com/ruisibi/datawrite/assets/28436981/ac7d63ba-7e94-4436-8944-94ca861f65de)

**Comment by ruisibi** [comment]
已修复
